% cleans an excel file generated by 'AvgStimSingle_test.m'
function clean(Excel) 
	if isa(Excel,'COM.Excel_Application')

		sheets = Excel.ActiveWorkBook.sheets;

		% loop through sheets
		for i=1:sheets.Count

			sheets.Item(i).Activate;
			sheet = Excel.ActiveSheet;

			disp(sheet.name)

			j = 2; % start at 2 to skip the header
            while j<sheet.UsedRange.Rows.Count
                if isnan(sheet.UsedRange.Rows.Item(j).Value{10})
                    sheet.UsedRange.Rows.Item(j).Delete;
                    j = j-1;
                end
                j = j+1;
            end	
		end
	end
end