function importfile(filetoread1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 09-Nov-2011 14:18:37

% Import the file
fileToRead1 = '004_base.txt';
newData1 = importdata('004_base.txt');

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData1);
for i = 1:length(vars)
    assignin('base', vars{i}, newData1.(vars{i}));
end

whos data